<?php
namespace Database\Seeders;

use App\Models\Organization;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrganizationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $organizations = [
            [
                "id" => 1,
                "name" => "Jaba Enterprises",
                "logo" => "profiles/2/enEKE7b4UIcTRDhew9MozvAHuAq04piWa9aXuNN0.png",
                "type" => "CUSTOMER",
                "admin_user_id" => 3,
                "created_by" => 3,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-03-27 18:08:06",
                "updated_at" => "2024-09-03 12:01:50",
                "is_test" => 0,
                "last_login" => "2024-09-03 12:01:49",
                "modified_by" => 2,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "2024-05-21 16:05:47",
            ],
            [
                "id" => 2,
                "name" => "Sampath CU",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 4,
                "created_by" => 4,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "Admin Control > APPROVE",
                "created_at" => "2024-03-31 05:04:35",
                "updated_at" => "2024-04-02 14:58:57",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 2,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 3,
                "name" => "Green Tech",
                "logo" => "profiles/5/GkjRLfC0lsn6Ejl18stDfO2ZMxrf3koUpEjxf9kO.jpg",
                "type" => "CUSTOMER",
                "admin_user_id" => 5,
                "created_by" => 5,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-04-17 04:25:31",
                "updated_at" => "2024-07-31 01:50:42",
                "is_test" => 1,
                "last_login" => "2024-07-30 22:50:42",
                "modified_by" => 5,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "2024-04-23 01:35:17",
            ],
            [
                "id" => 4,
                "name" => "Test 2 Yellow",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 6,
                "created_by" => 6,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-04-19 12:18:49",
                "updated_at" => "2024-05-14 18:43:33",
                "is_test" => 0,
                "last_login" => "2024-05-14 15:43:33",
                "modified_by" => 6,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "2024-04-19 09:35:09",
            ],
            [
                "id" => 5,
                "name" => "Test 3 Yellow",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 7,
                "created_by" => 7,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "Admin Control > APPROVE",
                "created_at" => "2024-04-19 12:24:47",
                "updated_at" => "2024-04-19 12:36:07",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 2,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 6,
                "name" => "Bank 1",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 8,
                "created_by" => 8,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "Admin Control > APPROVE",
                "created_at" => "2024-04-19 12:43:27",
                "updated_at" => "2024-05-09 16:28:38",
                "is_test" => 1,
                "last_login" => NULL,
                "modified_by" => 2,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 7,
                "name" => "Test 3",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 9,
                "created_by" => 9,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-04-19 12:48:25",
                "updated_at" => "2024-04-19 12:53:44",
                "is_test" => 0,
                "last_login" => "2024-04-19 09:50:37",
                "modified_by" => 9,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "2024-04-19 09:53:44",
            ],
            [
                "id" => 8,
                "name" => "SASCU",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 13,
                "created_by" => 13,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-04-25 15:45:54",
                "updated_at" => "2024-04-26 19:56:05",
                "is_test" => 0,
                "last_login" => "2024-04-26 16:56:05",
                "modified_by" => 11,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 9,
                "name" => "BLU",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 12,
                "created_by" => 12,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "PENDING",
                "modified_section" => NULL,
                "created_at" => "2024-04-26 03:27:29",
                "updated_at" => "2024-04-26 03:27:29",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 2,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 10,
                "name" => "Organization A",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 13,
                "created_by" => 13,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "PENDING",
                "modified_section" => NULL,
                "created_at" => "2024-04-27 16:23:04",
                "updated_at" => "2024-05-09 16:24:38",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 1,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 11,
                "name" => "Test 10",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 14,
                "created_by" => 14,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "PENDING",
                "modified_section" => NULL,
                "created_at" => "2024-04-29 05:01:21",
                "updated_at" => "2024-05-09 16:25:53",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 27,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 12,
                "name" => "SASCUTEST",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 15,
                "created_by" => 15,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-05-08 17:49:12",
                "updated_at" => "2024-05-10 15:05:00",
                "is_test" => 0,
                "last_login" => "2024-05-10 12:05:00",
                "modified_by" => 15,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 68,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 13,
                "name" => "Sharons Credit Union",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 16,
                "created_by" => 16,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "PENDING",
                "modified_section" => NULL,
                "created_at" => "2024-05-23 17:28:43",
                "updated_at" => "2024-05-23 17:28:43",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 67,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 14,
                "name" => "James Company",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 17,
                "created_by" => 17,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "ACTIVE",
                "modified_section" => "last_login",
                "created_at" => "2024-05-29 14:25:28",
                "updated_at" => "2024-06-18 19:57:42",
                "is_test" => 1,
                "last_login" => "2024-06-18 16:57:42",
                "modified_by" => 17,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 6,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
            [
                "id" => 15,
                "name" => "guest",
                "logo" => NULL,
                "type" => "CUSTOMER",
                "admin_user_id" => 18,
                "created_by" => 18,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "status" => "PENDING",
                "modified_section" => NULL,
                "created_at" => "2024-06-23 09:37:35",
                "updated_at" => "2024-06-23 09:37:35",
                "is_test" => 0,
                "last_login" => NULL,
                "modified_by" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "users_limit" => 5,
                "naics_code_id" => NULL,
                "potential_yearly_deposit_id" => NULL,
                "wholesale_deposit_portfolio_id" => NULL,
                "allow_multi_organizations" => 0,
                "requires_to_confirm_users_seats" => 0,
                "digital_account_opening" => NULL,
                "accepted_terms_and_conditions" => 1,
                "sign_up_from" => NULL,
                "needs_update" => "yes",
                "industry_id" => 1,
                "is_partially_approved" => NULL,
                "last_self_assessment_date" => "0000-00-00 00:00:00",
            ],
        ];

        foreach ($organizations as $org) {
            // Check if the organization with the given name exists
            $existingOrg = Organization::where('name', $org['name'])->first();

            if (!$existingOrg) {
                // Create a new organization if it doesn't already exist
                Organization::create([
                    'name' => $org['name'],
                    'admin_user_id' => $org['admin_user_id'],
                    'created_by' => $org['created_by'],
                    'last_login' => $org['last_login'],
                    'status' => $org['status']
                ]);
            }
        }
    }
}
