<?php

namespace Database\Seeders;

use App\Models\ScopeOneEmissionCategory;
use App\Models\ScopeTwoEmissionCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ScopeTwoEmissionCategoriesSeeder extends Seeder
{
   /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $scope_two_emission_inventory_categories = [
            [
                "id" => 1,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "British Columbia",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 15.00000,
            ],
            [
                "id" => 2,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Alberta",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 540.00000,
            ],
            [
                "id" => 3,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Saskatchewan",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 730.00000,
            ],
            [
                "id" => 4,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Manitoba",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 2.00000,
            ],
            [
                "id" => 5,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Ontario",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 30.00000,
            ],
            [
                "id" => 6,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Quebec",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 1.70000,
            ],
            [
                "id" => 7,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "New Brunswick",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 300.00000,
            ],
            [
                "id" => 8,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Nova Scotia",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 690.00000,
            ],
            [
                "id" => 9,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Prince Edward Island",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 300.00000,
            ],
            [
                "id" => 10,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Newfoundland and Labrador",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 17.00000,
            ],
            [
                "id" => 11,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Yukon",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 80.00000,
            ],
            [
                "id" => 12,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Northwest Territories",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 170.00000,
            ],
            [
                "id" => 13,
                "group" => "Purchased Electricity:  Indirect emissions from electricity generated by an utility provider and purchased for organizational use",
                "name" => "Nunavut",
                "form" => "forAll",
                "created_at" => "2024-08-21 03:57:27",
                "updated_at" => "2024-08-21 03:57:27",
                "factor" => 840.00000,
            ],
        ];

        foreach ($scope_two_emission_inventory_categories as $item) {
            // Check if the category with the given name already exists
            $scope_two = ScopeTwoEmissionCategory::where('name', $item['name'])->first();

            if (!$scope_two) {
                // Create a new category if it doesn't already exist
                ScopeTwoEmissionCategory::create([
                    'id'=>$item['id'],
                    'group' => $item['group'],
                    'name' => $item['name'],
                    'factor' => $item['factor'],
                ]);
            }
        }
    }
}
