<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = array(
            array(
                "id" => 1,
                "name" => "Ozella Williamson",
                "profile_pic" => NULL,
                "email" => "njoshdavi@gmail.com",
                "account_opening_date" => "2024-03-24 07:25:59",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-08-10 01:22:37",
                "modified_section" => "Admin Control > Unsuspend Account",
                "modified_by" => 2,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-05-05 13:14:49",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Ozella",
                "lastname" => "Williamson",
                "switched_organization_id" => 1,
                "is_system_admin" => 1,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "Sampath Ekanayake",
                "profile_pic" => "profiles/2/iUW9giuV5cgSY3cyBndbbLLoVzpfhmVM5GqbQzZE.png",
                "email" => "dwaichari@gmail.com",
                "account_opening_date" => "2024-03-24 05:36:05",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-09-03 12:01:50",
                "modified_section" => "last_login",
                "modified_by" => 2,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-09-03 12:01:49",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Sampath",
                "lastname" => "Ekanayake",
                "switched_organization_id" => 1,
                "is_system_admin" => 1,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "name" => "Angela Basset",
                "profile_pic" => NULL,
                "email" => "bspokekenya@gmail.com",
                "account_opening_date" => "2024-03-27 15:08:06",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-06-11 14:59:04",
                "modified_section" => "last_login",
                "modified_by" => 3,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-06-11 14:59:04",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Angela",
                "lastname" => "Basset",
                "switched_organization_id" => 1,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => "{\"dnt\": [\"1\"], \"host\": [\"climatrix.ca\"], \"accept\": [\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\"], \"cookie\": [\"__gsas=ID=f7c98a1e0c0fa7c0:T=1711615337:RT=1711615337:S=ALNI_MZSafEvzColbRDD9N7qBMQFPs1xQg; pvisitor=b71d47d8-0544-4e45-b9ab-8039beaba3e1; XSRF-TOKEN=eyJpdiI6IlJPbEgrN1RRSlZHUzhhRXBNcFNoaUE9PSIsInZhbHVlIjoiU1FsQkJXY05VR3FSVHZZWWtwakxsZklGS3BDSW9McEJtRWNxbnVSUmtoZEVUM0RERFFpcjUrOUpOakhvSGR2NkJ6bE8ralNTTVJ4Zm9QMFdvM1V1QXRON2RoZXppUWJYdXVROXZIYzFVZVN6aUlRbmFuWll3Y0NmbVp3L1Y3V1AiLCJtYWMiOiI1Y2E2YmNhMmE0N2UxZGNiZTcwMjFiYmY2OGMyOTU5ZDE4NWE5N2ZjYTY2OWU1NzIyOTBlZmVhMmVkNTlmM2I3IiwidGFnIjoiIn0%3D; climatrix_session=eyJpdiI6IldEZWltU0o1dExjQ1NxNzhnQ2ZralE9PSIsInZhbHVlIjoiendmejFNbnJyeTdwQ0hNQk9BZHlIUzhObG9WN0NHMG9jOUticnJrQlNnYXZ0WXVXUkJuRDVlZDhsdmtESi80VVRFSlNWK0QyMUpnTU9HYjJJS0RwSjQ0SVlESCtqSk9VZmpDNXFxVldSQ2lpOUJsaGtnMnpKWXExWVFkOVQzQkYiLCJtYWMiOiI4MTFkNDBhZWY3ZDI2MzBmYjE2OTE3YjAyZjZmODAyN2VlNjJkYjZhNWYxZDEyNWEwODk2NDU4ZWQ4ZDU3ZTIzIiwidGFnIjoiIn0%3D\"], \"referer\": [\"https://climatrix.ca/climatrix-admin/users/customers\"], \"sec-ch-ua\": [\"\\\"Google Chrome\\\";v=\\\"123\\\", \\\"Not:A-Brand\\\";v=\\\"8\\\", \\\"Chromium\\\";v=\\\"123\\\"\"], \"x-user-ip\": [null], \"connection\": [\"keep-alive\"], \"user-agent\": [\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36\"], \"sec-fetch-dest\": [\"document\"], \"sec-fetch-mode\": [\"navigate\"], \"sec-fetch-site\": [\"same-origin\"], \"sec-fetch-user\": [\"?1\"], \"accept-encoding\": [\"gzip, deflate, br, zstd\"], \"accept-language\": [\"en-US,en;q=0.9\"], \"sec-ch-ua-mobile\": [\"?0\"], \"sec-ch-ua-platform\": [\"\\\"Windows\\\"\"], \"upgrade-insecure-requests\": [\"1\"]}",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "name" => "Sampath Ekanayake",
                "profile_pic" => NULL,
                "email" => "hmkbh2018@gmail.com",
                "account_opening_date" => "2024-03-31 02:04:35",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-04-02 11:58:57",
                "modified_section" => "Admin Organization Control > ACTIVE",
                "modified_by" => 2,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Sampath",
                "lastname" => "Ekanayake",
                "switched_organization_id" => 2,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "name" => "Dheelaka Amarasekara",
                "profile_pic" => "profiles/5/rev7PHpPkcYIlS8gA4XNlvQB8MxsDDy2Rch4ZTx0.jpg",
                "email" => "dheelakamaster@gmail.com",
                "account_opening_date" => "2024-04-17 01:25:31",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-07-30 22:50:42",
                "modified_section" => "last_login",
                "modified_by" => 5,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-07-30 22:50:42",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 1,
                "firstname" => "Dheelaka",
                "lastname" => "Amarasekara",
                "switched_organization_id" => 3,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "name" => "Test 2 Mike",
                "profile_pic" => NULL,
                "email" => "yieldtestdepo@gmail.com",
                "account_opening_date" => "2024-04-19 09:18:49",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-05-20 15:49:11",
                "modified_section" => "failed_login_attempts",
                "modified_by" => 6,
                "failed_login_attempts" => 1,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-05-14 15:43:33",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Test 2",
                "lastname" => "Mike",
                "switched_organization_id" => 4,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "name" => "Test 3 Viviyane",
                "profile_pic" => NULL,
                "email" => "Chinthanajayalath@yieldexchange.ca",
                "account_opening_date" => "2024-04-19 09:24:47",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-04-19 09:36:07",
                "modified_section" => "Admin Organization Control > ACTIVE",
                "modified_by" => 2,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Test 3",
                "lastname" => "Viviyane",
                "switched_organization_id" => 5,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "name" => "Leyla Test",
                "profile_pic" => NULL,
                "email" => "Chinthana.jayalath@yieldexchange.ca",
                "account_opening_date" => "2024-04-19 09:43:27",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-04-24 11:56:11",
                "modified_section" => "Admin Organization Control > ACTIVE",
                "modified_by" => 2,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 1,
                "firstname" => "Leyla",
                "lastname" => "Test",
                "switched_organization_id" => 6,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "name" => "Bike Test",
                "profile_pic" => NULL,
                "email" => "veyakat918@etopys.com",
                "account_opening_date" => "2024-04-19 09:48:25",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-04-19 09:50:37",
                "modified_section" => "last_login",
                "modified_by" => 9,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-04-19 09:50:37",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Bike",
                "lastname" => "Test",
                "switched_organization_id" => 7,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "name" => "Leyla Climatric",
                "profile_pic" => NULL,
                "email" => "dheelakamaster@gmail.com",
                "account_opening_date" => "2024-04-21 04:00:07",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-06-26 07:04:21",
                "modified_section" => "last_login",
                "modified_by" => 10,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-06-26 07:04:21",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Leyla",
                "lastname" => "Climatric",
                "switched_organization_id" => 1,
                "is_system_admin" => 1,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "name" => "Doug Ebner",
                "profile_pic" => NULL,
                "email" => "dougebner@sascu.com",
                "account_opening_date" => "2024-04-25 12:45:54",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-04-26 16:56:05",
                "modified_section" => "last_login",
                "modified_by" => 11,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-04-26 16:56:05",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Doug",
                "lastname" => "Ebner",
                "switched_organization_id" => 8,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "name" => "Ranil wickramasiri",
                "profile_pic" => NULL,
                "email" => "waxor63805@haislot.com",
                "account_opening_date" => "2024-04-26 00:27:29",
                "account_status" => "PENDING",
                "modified_date" => NULL,
                "modified_section" => NULL,
                "modified_by" => NULL,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Ranil",
                "lastname" => "wickramasiri",
                "switched_organization_id" => 9,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "name" => "Ea nobis consequatur Ut voluptatem offici",
                "profile_pic" => NULL,
                "email" => "pywody@mailinator.com",
                "account_opening_date" => "2024-04-27 13:23:04",
                "account_status" => "PENDING",
                "modified_date" => NULL,
                "modified_section" => NULL,
                "modified_by" => NULL,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Ea nobis consequatur",
                "lastname" => "Ut voluptatem offici",
                "switched_organization_id" => 10,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "name" => "Test Mike",
                "profile_pic" => NULL,
                "email" => "hiwanag134@buzblox.com",
                "account_opening_date" => "2024-04-29 02:01:21",
                "account_status" => "PENDING",
                "modified_date" => NULL,
                "modified_section" => NULL,
                "modified_by" => NULL,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Test",
                "lastname" => "Mike",
                "switched_organization_id" => 11,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "name" => "Breanna Jeebe",
                "profile_pic" => NULL,
                "email" => "breannajeebe@sascu.com",
                "account_opening_date" => "2024-05-08 14:49:12",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-05-10 12:05:00",
                "modified_section" => "last_login",
                "modified_by" => 15,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-05-10 12:05:00",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Breanna",
                "lastname" => "Jeebe",
                "switched_organization_id" => 12,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "name" => "Chuck Lew",
                "profile_pic" => NULL,
                "email" => "clew@sharons.ca",
                "account_opening_date" => "2024-05-23 14:28:43",
                "account_status" => "PENDING",
                "modified_date" => NULL,
                "modified_section" => NULL,
                "modified_by" => NULL,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "Chuck",
                "lastname" => "Lew",
                "switched_organization_id" => 13,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "name" => "James Muriithi",
                "profile_pic" => NULL,
                "email" => "muriithijames556@gmail.com",
                "account_opening_date" => "2024-05-29 11:25:28",
                "account_status" => "ACTIVE",
                "modified_date" => "2024-06-18 16:57:42",
                "modified_section" => "last_login",
                "modified_by" => 17,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => "2024-06-18 16:57:42",
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 1,
                "firstname" => "James",
                "lastname" => "Muriithi",
                "switched_organization_id" => 14,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "name" => "john doe",
                "profile_pic" => NULL,
                "email" => "ekiromo21@gmail.com",
                "account_opening_date" => "2024-06-23 06:37:35",
                "account_status" => "PENDING",
                "modified_date" => NULL,
                "modified_section" => NULL,
                "modified_by" => NULL,
                "failed_login_attempts" => 0,
                "account_closure_date" => NULL,
                "account_closure_reason" => NULL,
                "last_login" => NULL,
                "created_by" => NULL,
                "password_changed" => 0,
                "account_manager" => NULL,
                "inviter_name" => NULL,
                "is_test" => 0,
                "firstname" => "john",
                "lastname" => "doe",
                "switched_organization_id" => 15,
                "is_system_admin" => 0,
                "requires_password_update" => 0,
                "admin_loggedin_as" => NULL,
                "admin_loggedin_as_agent" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );


        foreach ($users as $user) {
            // Check if the user with the given email already exists
            $available = User::where('email', $user['email'])->first();

            if (!$available) {
                // Create a new user if they don't already exist
                User::create([
                    'id' => $user['id'],
                    'name' => $user['name'],
                    'first_name' => $user['firstname'],
                    'last_name' => $user['lastname'],
                    'is_system_admin'=> $user['is_system_admin'],
                    'last_login'=>$user['last_login'],
                    'account_opening_date' => $user['account_opening_date'],
                    'account_status'=>$user['account_status'],
                    "failed_login_attempts" => $user['failed_login_attempts'],
                    "account_closure_date" => $user['account_closure_date'],
                    "account_closure_reason" => $user['account_closure_reason'],
                    'email' => $user['email'],
                    'created_by'=>$user['created_by'],
                    'created_at'=>$user['created_at'],
                    'updated_at'=>$user['updated_at'],
                    'password' => bcrypt('1234'),
                     // Default password
                ]);
            }
        }
    }
}
